### PR TITLE
Issue #3 Fix - Added capability for continuous increments/decrements on scroll buttons long press

### PR DESCRIPTION
**Pull request by jasmap**
Good Day

Have added the capability for continuous value change on scroll buttons long press. Let me know if I need to adjust anything. Thanks

### CODE REVIEW

**Comment by jasmap** [comment]
I think we solved it, added the mouseleave event listener on both scroll buttons. Thanks @nadchif for the help

**Comment by jasmap** [comment]
Thanks for the approval

**Comment by nadchif** [comment]
Thank you @jasmap for this awesome feature enhancement. If you spot anymore issues or think of other enhancement features, please feel welcome to open an issue.

**Comment by nadchif** [comment]
@all-contributors please add @jasmap for code

**Pull request merged**
