### PR TITLE
Update to remove unnecessary focus  

### PR DESCRIPTION
**Pull request by Kharanshu31**
line number 386 was unnecessarily focusing the picker when mouse moves away

### CODE REVIEW

**Comment by Kharanshu31** [comment]
Please tell me if it is accepted

**Comment by Kharanshu31** [comment]
Sorry for the check fail but it can be resolved if we remove line 365 and the extra space

**Comment by nadchif** [comment]
> line number 386 was unnecessarily focusing the picker when mouse moves away

You certainly got that right! Great job 👏  
I've modified your code a bit, because we still need the mouseleave event focus, if the buttons were clicked. 

Please take a look, and let me know if there are any concerns before I go ahead and merge

**Comment by Kharanshu31** [comment]
The above changes looks good

**Comment by nadchif** [comment]
Thank you for your contribution. @all-contributors please add @Kharanshu31 for code

**Pull request merged**
