### PR TITLE
fix for angular issue.

### PR DESCRIPTION
**Pull request by wyntonfranklin**
fix angular model values not updating

### CODE REVIEW

**Comment by nadchif** [comment]
Hi @wyntonfranklin thank you for the contribution to solving the angular issue. I've refactored a bit in order to still have ` intervalId = setInterval(changeValueByArrowKeys, 200, inputBox, 'down'/'up')` working.
It is used when users click and hold down the mouse on up or down buttons.

May please push the commits to this branch and please let me know if everything still works as expected in Angular

**Comment by wyntonfranklin** [comment]
Sure I'll check it out

**Comment by wyntonfranklin** [comment]
Hi @nadchif it works as expected. No issues in angular.

**Comment by nadchif** [comment]
Thank you @wyntonfranklin. As there are now some issues with the unit tests, I commented out [this part ](https://github.com/nadchif/html-duration-picker.js/blob/2e8ff9b97897be6ba2a6a6c04b28221b41d0115c/src/html-duration-picker.js#L141).
I will also merge this to a `dev` branch and later investigate what's going on with the unit tests 🙂

**Pull request merged**
